### ISSUE TITLE
General Localization

### ISSUE THREAD

**Issue by xevilcorp** [xevilcorp/We.Share#4]
Localization has the purpose of displaying the UI elements based on the user culture, this allows the software to be multi-language and more accessible for users in different countries.

**TASKS**
- [ ] Prepare the environment for localization
- [ ] Create resx files with keys and values for languages
- [ ] Display values based on the user language
